cawasa/cawasa/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^stocks/', include('stocks.urls')),
    url(r'^screener/', include('screener.urls')),
    url(r'^admin/', admin.site.urls),
]

cawasa/screener/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

cawasa/stocks/urls.py
from django.conf.urls import url

from . import views

app_name = 'stocks'  # Needed for namespacing with templates - 'stocks:summary'
urlpatterns = [
    url(r'^$', views.index, name='index'),
#    url(r'^(?P<stock_id>[0-9]+)/$', views.summary, name='summary'),
    url(r'^(?P<pk>[0-9]+)/$', views.SummaryView.as_view(), name='summary'),   # generic view
    url(r'^indexes/$', views.IndexView.as_view(), name='indexes'),  # generic view

    url(r'^indexes/(?P<index_id>[0-9]+)/$', views.index_history, name='index_history'),
    # url(r'^indexes/(?P<pk>[0-9]+)/$', views.IndexHistoryView.as_view(), name='index_history'),

    url(r'^index/(?P<index_id>[0-9]+)/names/$', views.index_names, name='index_names'),
]

# url(r'^(?P<stock_id>[0-9]+)/$', views.summary, name='summary'),   # non-generic view

cawasa/screener/models.py
from __future__ import unicode_literals

from django.db import models

cawasa/stocks/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib import admin
#from django.forms import CheckBoxSelectMultiple



class Stock(models.Model):
    name = models.CharField(max_length=50)
    symbol = models.CharField(max_length=8)
    sector = models.CharField(max_length=50, blank=True)
    industry = models.CharField(max_length=75, blank=True)
    #description = models.CharField(max_length=500, blank=True)
    #indexes = models.ManyToManyField(Index, blank=True)

    COMMON_STOCK = 'CS'
    EXCHANGE_TRADED_FUND = 'ETF'
    MUTUAL_FUND = 'MF'
    BOND = 'B'
    TYPE_CHOICES = (
        (COMMON_STOCK, 'Common Stock'),
        (EXCHANGE_TRADED_FUND, 'ETF'),
        (MUTUAL_FUND, 'Mutual Fund'),
        (BOND, 'Bond'),
    )
    type = models.CharField(max_length=3, choices=TYPE_CHOICES, default=COMMON_STOCK)

    def __str__(self):
        return self.name


class Index(models.Model):
    name = models.CharField(max_length=50)
    symbol = models.CharField(max_length=8)
    description = models.CharField(max_length=500, blank=True)

    def __str__(self):
        return self.symbol


class IndexHistory(models.Model):
    date = models.DateField()
    index = models.ForeignKey(Index)
    stock = models.ForeignKey(Stock)

    def __str__(self):
        printable_date = self.date.strftime("%m/%d/%Y")
        return printable_date + '\t' + str(self.index) + '\t' + str(self.stock)

cawasa/stocks/forms.py
from django import forms

class SymbolLookup(forms.Form):
    symbol_lookup = forms.CharField(label='Symbol Lookup', max_length=100)

cawasa/screener/views.py
from django.shortcuts import render

from django.http import HttpResponse

def index(request):
    return HttpResponse("Hello, world.  You're at the screener index.")

cawasa/stocks/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.http import Http404
from django.template import loader
from django.views import generic
from django.views import generic
from .models import Stock, Index, IndexHistory
from .forms import SymbolLookup
#import difflib


def index(request):
    """ Return rendered all stocks orderd by symbol, stock lookup form,
        and any results from a stock lookup.
    """
    lookup_stocks = None
    if request.method == 'POST':  # If loaded from form (symbol lookup)
        form = SymbolLookup(request.POST)  # Form object with POST data
        if form.is_valid():
            symbol_lookup = form.cleaned_data['symbol_lookup']
            try:
                # Try to get an exact match on POST data
                exact_match = Stock.objects.get(symbol__iexact=symbol_lookup)
                return HttpResponseRedirect(exact_match.pk)
            except Stock.DoesNotExist:     # If no exact match
                lookup_stocks = Stock.objects.filter(symbol__icontains=
                                                     symbol_lookup).order_by(
                                                        'symbol')
                if not lookup_stocks:
                    lookup_stocks = '0'
    else:
        form = SymbolLookup()

    all_names = Stock.objects.order_by('symbol')
    ##template = loader.get_template('stocks/index.html')
    context = {'all_stocks_list': all_names, 'form': form, 'stock_lookup_list': lookup_stocks}
    return render(request, 'stocks/index.html', context)


def index_history(request, index_id):
    """ Returns rendered historical list of stocks within an index for
        index_id
    """
    ih = get_object_or_404(IndexHistory, pk=index_id)
    context = {'index_member_history': ih}
    return render(request, 'stocks/index_history.html', context)


class SummaryView(generic.DetailView):
    """ Generic View for the summary details of a stock """
    model = Stock
    template_name = 'stocks/summary.html'

#def summary(request, stock_id):
#    stock = get_object_or_404(Stock, pk=stock_id)
#    #try:
#    #    stock = Stock.objects.get(pk=stock_id)
#    #except Stock.DoesNotExist:
#    #    raise Http404("Stock is not currently in the DB.")
#    return render(request, 'stocks/summary.html', {'stock':stock})
#    #return HttpResponse("This will display the summary for stock with id = %s" % stock_id)


class IndexView(generic.ListView):
    """ Generic View for a listing of recorded indexes """
    model = Index
    template_name = 'stocks/indexes.html'


# class IndexHistoryView(generic.ListView):
#     model = IndexHistory
#     context_object_name = 'index_members_history'
#     template_name = 'stocks/index_hist# class IndexHistoryView(generic.ListView):
#     model = IndexHistory
#     context_object_name = 'index_members_history'
#     template_name = 'stocks/index_history.html'

    # def get_queryset(self):
    #     self.index = get_object_or_404(IndexHistory, pk=self.args[0])
    #     return IndexHistory.objects.filter(index=self.index)
    #
    # def get_context_data(self, **kwargs):
    #     context = super(IndexHistoryView, self).get_context_data(**kwargs)
    #     context['index'] = self.index
    #     return context


def index_names(request, index_id):
    return HttpResponse("This will return a list of names in index %s" % index_id)




#def symbol_lookup(request):
##    if request.method == 'POST':
#        form = SymbolLookup(request.POST)
#        if form.is_valid():
#            return HttpResponseRedirect('/thanks/')
#    else:
#        form = SymbolLookup()#

#    return render(request, 'stocks/index.html', {'form': form})

cawasa/stocks/templates/stocks/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> CAWASA </title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'stocks/style.css' %}" />
<body>

{% block header %}
    <header id="page-header">
        <span id="header-logo">CAWASA</span>
        <ul class="navbar">
            <li class="navbar"><a href="/stocks/">STOCKS</a></li>
            <li class="navbar"><a href="/stocks/indexes/">INDEXES</a></li>
        </ul>
    </header>
{% endblock header %}

{% block content %}
{% endblock content %}

</body>
</html>

cawasa/stocks/templates/stocks/index.html
{% extends 'stocks/base.html' %}

{% block content %}

<div id="main-box">

    <div id="list-title">
        <h1 style="float: left; display: inline;">Stock Symbols</h1>
        <div id="stock-symbol-lookup">
            <form action="" method="POST">
                {% csrf_token %}
                <!--{{ form }}  Uses standard django form-->
                {% for field in form %}
                    {{ field.label_tag }} {{ field }}
                {% endfor %}
                <input type="submit" value="Search" />
            </form>
        </div>
    </div>

    <div id="stock-symbol-lookup-results">
        {% if stock_lookup_list %}
            {% if stock_lookup_list == '0' %}
                <h3>No matches.</h3>
            {% else %}
                <h5>Possible Lookup Matches:</h5>
                <ul style="list-style-type:none">
                    {% for stock in stock_lookup_list %}
                        <li><a class="list" href="{% url 'stocks:summary' stock.id %}">{{ stock.symbol }}</a></li>
                    {% endfor %}
                </ul>
            {% endif %}
        {% endif %}
    </div>



    <div id="data-list">
        {% if all_stocks_list %}
            <ul>
                {% for stock in all_stocks_list %}
                    <li><a class="list" href="{% url 'stocks:summary' stock.id %}">{{ stock.symbol }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No stocks are available.</p>
        {% endif %}
    </div>

</div>

{% endblock content %}

cawasa/stocks/templates/stocks/index_history.html
{% extends 'stocks/base.html' %}

{% block content %}

<div id="main-box">

    <div>
        {% for index in index_member_history %}
            <h2> {{ index }}</h2>
        {% endfor %}
    </div>
    <div id="list-title">
        <h1 style="float: left; display: inline;">{{ object.index }}</h1>
    </div>

    <h1>S&P 500</h1>
    <ul>
        {% for obj in object_list %}
            <li><span style="margin-right:2em">{{ obj.date }} </span>
                - <span style="margin-left:2em"> {{ obj.index }}</span></li>
        {% endfor %}
    </ul>

</div>

{% endblock content %}

cawasa/stocks/templates/stocks/indexes.html
{% extends 'stocks/base.html' %}

{% block content %}
<div id="main-box">

    <div id="list-title">
        <h1 style="float: left; display: inline;">Stock Index List</h1>
    </div>
        <style>
            .symbol-box {
                display: inline;
                float: left;
                margin: 10px 0;
                width: 5%;
            }
            .gap-box{
                display: inline;
                float: left;
                margin: 10px 0;
                width: 5%;
            }
            .name-box {
                display: inline;
                float: left;
                margin: 10px 0;
                width: 30%;
            }
        </style>
        <div id="data-list">
        {% for index in object_list %}
            <ul style="list-style-type: none">
                <li>
                    <a class="list" href="{% url 'stocks:index_history' index.id %}">
                        <div class="symbol-box">{{ index.symbol }}</div>
                        <div class="gap-box">--</div>
                        <div class="name-box">{{ index.name }}</div>
                        </br></br>
                    <a/>
                </li>
            </ul>
        {% endfor %}
        </div>

</div>

{% endblock content %}

cawasa/stocks/templates/stocks/summary.html
{% extends 'stocks/base.html' %}

{% block content %}
<div id="main-box">

    <div id="list-title">
        <h1 style="float: left; display: inline;">Summary for {{ stock.name }}</h1>
    </div>

    <div id="data-list">
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

        <style>
            table, th, td {
                border: 2px solid black;
                border-collapse: collapse;
            }
            th, td {
                padding: 15px;
            }
        </style>
        <table style="width:100%">
            <tr>
                <td>Symbol</td>
                <td>{{ stock.symbol }}</td>
            </tr>
            <tr>
                <td>Industry</td>
                <td> {{ stock.industry }}</td>
            </tr>
            <tr>
                <td>Sector</td>
                <td> {{ stock.sector }}</td>
            </tr>
            <tr>
                <td>Type</td>
                <td> {{ stock.type }}</td>
            </tr>
        </table>
    </div>

</div>

{% endblock content %}